import { ParkingSpot, UserProfile, Booking, ListedSpot } from '../types';

// ─── USER ────────────────────────────────────────────────────────────────────
export const currentUser: UserProfile = {
  name: 'Prisha Sharma',
  rollNumber: 'CHD-2024-1923',
  trustScore: 98,
  spotsVerified: 42,
  phantomSpotsOverridden: 5,
  walletBalance: 380,
  vehicleType: 'Car',
  vehicleNumber: 'CH01-AB-5678',
  totalParkings: 87,
  moneySaved: 620,
  emergencyContact: '+91-9876543210',
  emergencyContactName: 'Rahul Sharma (Father)',
};

// ─── CHANDIGARH SPOTS ────────────────────────────────────────────────────────
export const CHANDIGARH_SPOTS: ParkingSpot[] = [
  {
    id: 'chd-1',
    latitude: 30.7333,
    longitude: 76.7794,
    title: 'Elante Mall Parking – Level B1',
    address: 'Industrial Area Phase 1, Chandigarh',
    confidence: 'High',
    status: 'Available',
    hasEV: true,
    basePrice: 40,
    dynamicPrice: 60,
    type: 'Car',
    isStreetParking: false,
    ownerName: 'Elante Parkings Pvt Ltd',
    ownerPhone: '+91-9876500001',
    rating: 4.7,
    totalRatings: 892,
    features: ['CCTV', 'Security Guard', 'EV Charging', 'Covered', 'Restroom'],
    openHours: '8:00 AM – 11:00 PM',
    distance: '0.4 km',
    estimatedArrival: '3 min',
    city: 'Chandigarh',
    totalSpots: 150,
    availableSpots: 42,
  },
  {
    id: 'chd-2',
    latitude: 30.7398,
    longitude: 76.7717,
    title: 'Sector 17 Plaza Parking',
    address: 'Sector 17, Chandigarh',
    confidence: 'High',
    status: 'Available',
    hasEV: false,
    basePrice: 30,
    dynamicPrice: 30,
    type: 'Car',
    isStreetParking: false,
    ownerName: 'CSCL Parking Authority',
    ownerPhone: '+91-9876500002',
    rating: 4.2,
    totalRatings: 411,
    features: ['CCTV', 'Covered', 'Security Guard'],
    openHours: '6:00 AM – 10:00 PM',
    distance: '0.7 km',
    estimatedArrival: '5 min',
    city: 'Chandigarh',
    totalSpots: 80,
    availableSpots: 12,
  },
  {
    id: 'chd-3',
    latitude: 30.7273,
    longitude: 76.7679,
    title: 'Sector 22 Market Bike Stand',
    address: 'Sector 22-B, Chandigarh',
    confidence: 'Medium',
    status: 'Available',
    hasEV: false,
    basePrice: 10,
    dynamicPrice: 15,
    type: 'Bike',
    isStreetParking: false,
    ownerName: 'Sukhwinder Singh',
    ownerPhone: '+91-9876500003',
    rating: 3.9,
    totalRatings: 102,
    features: ['Covered', 'Well-lit'],
    openHours: '7:00 AM – 9:00 PM',
    distance: '1.1 km',
    estimatedArrival: '7 min',
    city: 'Chandigarh',
    totalSpots: 40,
    availableSpots: 8,
  },
  {
    id: 'chd-4',
    latitude: 30.7440,
    longitude: 76.7847,
    title: 'PGI Hospital EV Bay',
    address: 'PGI Campus, Sector 12, Chandigarh',
    confidence: 'High',
    status: 'Available',
    hasEV: true,
    basePrice: 50,
    dynamicPrice: 50,
    type: 'EV',
    isStreetParking: false,
    ownerName: 'PGI Facility Mgmt',
    ownerPhone: '+91-9876500004',
    rating: 4.8,
    totalRatings: 330,
    features: ['Fast Charging', 'CCTV', 'Covered', '24x7 Security'],
    openHours: '24/7',
    distance: '0.9 km',
    estimatedArrival: '6 min',
    city: 'Chandigarh',
    totalSpots: 20,
    availableSpots: 4,
  },
  {
    id: 'chd-5',
    latitude: 30.7310,
    longitude: 76.7755,
    title: 'Sector 35 Street Parking',
    address: 'Sector 35-B, Chandigarh',
    confidence: 'Low',
    status: 'Phantom',
    hasEV: false,
    basePrice: 20,
    dynamicPrice: 20,
    type: 'Car',
    isStreetParking: true,
    ownerName: 'Gurpreet Kaur',
    ownerPhone: '+91-9876500005',
    rating: 2.8,
    totalRatings: 34,
    features: ['Open Air'],
    openHours: '24/7',
    distance: '1.5 km',
    estimatedArrival: '10 min',
    city: 'Chandigarh',
    totalSpots: 10,
    availableSpots: 0,
  },
  {
    id: 'chd-6',
    latitude: 30.7364,
    longitude: 76.7906,
    title: 'Rock Garden Parking Zone',
    address: 'Sector 1, Near Rock Garden, Chandigarh',
    confidence: 'High',
    status: 'Occupied',
    hasEV: false,
    basePrice: 25,
    dynamicPrice: 45,
    type: 'Car',
    isStreetParking: false,
    ownerName: 'City Tourism Dept',
    ownerPhone: '+91-9876500006',
    rating: 4.1,
    totalRatings: 560,
    features: ['CCTV', 'Security Guard', 'Well-lit'],
    openHours: '7:00 AM – 8:00 PM',
    distance: '2.1 km',
    estimatedArrival: '12 min',
    city: 'Chandigarh',
    totalSpots: 60,
    availableSpots: 0,
  },
];

// ─── MUMBAI SPOTS ─────────────────────────────────────────────────────────────
export const MUMBAI_SPOTS: ParkingSpot[] = [
  {
    id: 'mum-1',
    latitude: 19.0596,
    longitude: 72.8295,
    title: 'Bandra Kurla Complex P1',
    address: 'BKC, Bandra East, Mumbai',
    confidence: 'High',
    status: 'Available',
    hasEV: true,
    basePrice: 80,
    dynamicPrice: 120,
    type: 'Car',
    isStreetParking: false,
    ownerName: 'MMRDA Parking Corp',
    ownerPhone: '+91-9820000001',
    rating: 4.6,
    totalRatings: 1243,
    features: ['CCTV', '24x7 Security', 'EV Charging', 'Covered', 'Valet'],
    openHours: '24/7',
    distance: '0.2 km',
    estimatedArrival: '1 min',
    city: 'Mumbai',
    totalSpots: 300,
    availableSpots: 15,
  },
  {
    id: 'mum-2',
    latitude: 19.0765,
    longitude: 72.8777,
    title: 'Andheri Station East Parking',
    address: 'Andheri East, Mumbai',
    confidence: 'High',
    status: 'Available',
    hasEV: false,
    basePrice: 50,
    dynamicPrice: 70,
    type: 'Car',
    isStreetParking: false,
    ownerName: 'ParkSmart Mumbai',
    ownerPhone: '+91-9820000002',
    rating: 4.0,
    totalRatings: 783,
    features: ['CCTV', 'Covered', 'Security Guard'],
    openHours: '5:00 AM – 1:00 AM',
    distance: '0.5 km',
    estimatedArrival: '4 min',
    city: 'Mumbai',
    totalSpots: 120,
    availableSpots: 54,
  },
  {
    id: 'mum-3',
    latitude: 18.9220,
    longitude: 72.8347,
    title: 'Nariman Point Multi-level',
    address: 'Nariman Point, South Mumbai',
    confidence: 'High',
    status: 'Available',
    hasEV: true,
    basePrice: 100,
    dynamicPrice: 150,
    type: 'Car',
    isStreetParking: false,
    ownerName: 'MCGM Smart Parking',
    ownerPhone: '+91-9820000003',
    rating: 4.5,
    totalRatings: 2100,
    features: ['CCTV', 'EV Charging', 'Covered', '24x7', 'Premium'],
    openHours: '24/7',
    distance: '0.3 km',
    estimatedArrival: '2 min',
    city: 'Mumbai',
    totalSpots: 500,
    availableSpots: 89,
  },
  {
    id: 'mum-4',
    latitude: 19.1136,
    longitude: 72.8697,
    title: 'Powai Hiranandani Bike Bay',
    address: 'Hiranandani Gardens, Powai, Mumbai',
    confidence: 'Medium',
    status: 'Available',
    hasEV: false,
    basePrice: 20,
    dynamicPrice: 20,
    type: 'Bike',
    isStreetParking: false,
    ownerName: 'Hiranandani Estate Mgmt',
    ownerPhone: '+91-9820000004',
    rating: 4.3,
    totalRatings: 319,
    features: ['Covered', 'Well-lit', 'CCTV'],
    openHours: '6:00 AM – 11:00 PM',
    distance: '0.8 km',
    estimatedArrival: '5 min',
    city: 'Mumbai',
    totalSpots: 100,
    availableSpots: 32,
  },
  {
    id: 'mum-5',
    latitude: 19.0508,
    longitude: 72.9005,
    title: 'Kurla West Street Parking',
    address: 'LBS Marg, Kurla West, Mumbai',
    confidence: 'Low',
    status: 'Phantom',
    hasEV: false,
    basePrice: 30,
    dynamicPrice: 30,
    type: 'Car',
    isStreetParking: true,
    ownerName: 'Ramesh Yadav',
    ownerPhone: '+91-9820000005',
    rating: 2.5,
    totalRatings: 47,
    features: ['Open Air'],
    openHours: '24/7',
    distance: '1.4 km',
    estimatedArrival: '9 min',
    city: 'Mumbai',
    totalSpots: 15,
    availableSpots: 0,
  },
  {
    id: 'mum-6',
    latitude: 19.0178,
    longitude: 72.8478,
    title: 'Dadar TT Circle Parking',
    address: 'Dadar West, Mumbai',
    confidence: 'Medium',
    status: 'Occupied',
    hasEV: false,
    basePrice: 40,
    dynamicPrice: 60,
    type: 'Car',
    isStreetParking: false,
    ownerName: 'Dadar Park & Ride',
    ownerPhone: '+91-9820000006',
    rating: 3.7,
    totalRatings: 228,
    features: ['CCTV', 'Security Guard'],
    openHours: '6:00 AM – 11:00 PM',
    distance: '1.0 km',
    estimatedArrival: '7 min',
    city: 'Mumbai',
    totalSpots: 50,
    availableSpots: 0,
  },
];

export const MOCK_PARKING_SPOTS: ParkingSpot[] = [...CHANDIGARH_SPOTS, ...MUMBAI_SPOTS];

// ─── BOOKINGS ─────────────────────────────────────────────────────────────────
export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-001',
    spotId: 'chd-1',
    spotTitle: 'Elante Mall Parking – Level B1',
    address: 'Industrial Area Phase 1, Chandigarh',
    date: 'Today',
    startTime: '09:15 AM',
    amountPaid: 60,
    status: 'Active',
    vehicleNumber: 'CH01-AB-5678',
    transactionId: 'TXN-98234109',
    paymentMethod: 'Wallet',
  },
  {
    id: 'bk-002',
    spotId: 'mum-2',
    spotTitle: 'Andheri Station East Parking',
    address: 'Andheri East, Mumbai',
    date: 'Yesterday',
    startTime: '02:00 PM',
    endTime: '04:30 PM',
    duration: '2h 30m',
    amountPaid: 105,
    status: 'Completed',
    vehicleNumber: 'CH01-AB-5678',
    transactionId: 'TXN-98122934',
    paymentMethod: 'UPI',
  },
  {
    id: 'bk-003',
    spotId: 'mum-1',
    spotTitle: 'Bandra Kurla Complex P1',
    address: 'BKC, Bandra East, Mumbai',
    date: '24 Apr 2026',
    startTime: '10:00 AM',
    endTime: '11:45 AM',
    duration: '1h 45m',
    amountPaid: 180,
    status: 'Completed',
    vehicleNumber: 'CH01-AB-5678',
    transactionId: 'TXN-98001122',
    paymentMethod: 'Card',
  },
];

export const MOCK_LISTED_SPOTS: ListedSpot[] = [];

// ─── CITY CONFIG ──────────────────────────────────────────────────────────────
export const CITY_CONFIGS = {
  Chandigarh: {
    label: 'Chandigarh',
    region: {
      latitude: 30.7333,
      longitude: 76.7794,
      latitudeDelta: 0.06,
      longitudeDelta: 0.06,
    },
    spots: CHANDIGARH_SPOTS,
  },
  Mumbai: {
    label: 'Mumbai',
    region: {
      latitude: 19.0760,
      longitude: 72.8777,
      latitudeDelta: 0.12,
      longitudeDelta: 0.12,
    },
    spots: MUMBAI_SPOTS,
  },
};
